name: Continuous Integration

on: [push, pull_request]

jobs:
  build-1-58-1:
    name: "All tests: rustc 1.58.1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust 1.58.1
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: 1.58.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install cross-compilation toolchains
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib
          # For target: armv7-unknown-linux-gnueabihf
          sudo apt install -y gcc-arm-linux-gnueabihf
          # For target: aarch64-unknown-linux-gnu
          sudo apt install -y gcc-aarch64-linux-gnu
      - name: Execute all tests
        run: ./ci.sh
  build-stable:
    name: "All tests: rustc stable"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install cross-compilation toolchains
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib
          # For target: armv7-unknown-linux-gnueabihf
          sudo apt install -y gcc-arm-linux-gnueabihf
          # For target: aarch64-unknown-linux-gnu
          sudo apt install -y gcc-aarch64-linux-gnu
      - name: Execute all tests
        run: ./ci.sh
